config/routes.rb
Rails.application.routes.draw do
  resources :savedmsgs
  root 'welcome#index'
  get 'welcome/index'
  get '/messages/:id' => 'welcome#read'
  post '/' => 'welcome#new'
  post 'notes/api' => 'welcome#api'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/savedmsg.rb
class Savedmsg < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/savedmsgs_controller.rb
class SavedmsgsController < ApplicationController
  before_action :set_savedmsg, only: [:show, :edit, :update, :destroy]

  # GET /savedmsgs
  # GET /savedmsgs.json
  def index
    @savedmsgs = Savedmsg.all
  end

  # GET /savedmsgs/1
  # GET /savedmsgs/1.json
  def show
  end

  # GET /savedmsgs/new
  def new
    @savedmsg = Savedmsg.new
  end

  # GET /savedmsgs/1/edit
  def edit
  end

  # POST /savedmsgs
  # POST /savedmsgs.json
  def create
    @savedmsg = Savedmsg.new(savedmsg_params)

    respond_to do |format|
      if @savedmsg.save
        format.html { redirect_to @savedmsg, notice: 'Savedmsg was successfully created.' }
        format.json { render :show, status: :created, location: @savedmsg }
      else
        format.html { render :new }
        format.json { render json: @savedmsg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /savedmsgs/1
  # PATCH/PUT /savedmsgs/1.json
  def update
    respond_to do |format|
      if @savedmsg.update(savedmsg_params)
        format.html { redirect_to @savedmsg, notice: 'Savedmsg was successfully updated.' }
        format.json { render :show, status: :ok, location: @savedmsg }
      else
        format.html { render :edit }
        format.json { render json: @savedmsg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /savedmsgs/1
  # DELETE /savedmsgs/1.json
  def destroy
    @savedmsg.destroy
    respond_to do |format|
      format.html { redirect_to savedmsgs_url, notice: 'Savedmsg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_savedmsg
      @savedmsg = Savedmsg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def savedmsg_params
      params.require(:savedmsg).permit(:text)
    end
end

app/controllers/welcome_controller.rb
require 'nokogiri'
$curID = 0

def get_id
	$curID += 1
	return $curID
end

class WelcomeController < ApplicationController
	protect_from_forgery unless: -> {request.format.json? }
	def index
	end
	
	def read
	
		gid = params[:id]
			if(gid.to_i == -69)
				$curID = 0
				Savedmsg.delete_all
				return 0
			end
		data = Savedmsg.find_by_id(gid.to_i)
		if data.class == NilClass
			render plain: "ne"
			return 0
			end
		msg = data.send(:text).to_s
		render plain: msg
		Savedmsg.destroy(gid.to_i)
	end

	def new
		text = params[:text]
		id = get_id
		Savedmsg.create(:id => id, :text => text)
		a = "https://hw1312.herokuapp.com/messages/" + id.to_s
		render plain: a
	end
	
	def api
		data = request.headers["Content-Type"]
		
		if data == "application/json"
			danni = params[:message]
		elsif data == "text/xml"
			danni = Nokogiri::XML(request.body.read).content
		end
		
		id = get_id
		a = "https://hw1312.herokuapp.com/messages/" + id.to_s
		hash = Hash.new
		hash["url"] = a
		
		Savedmsg.create(:text => danni, :id => id)
		if data == "application/json"
			render json: hash
		elsif data == "text/xml"
			render xml: hash
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/savedmsgs_helper.rb
module SavedmsgsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/savedmsgs/_form.html.erb
<%= form_with(model: savedmsg, local: true) do |form| %>
  <% if savedmsg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(savedmsg.errors.count, "error") %> prohibited this savedmsg from being saved:</h2>

      <ul>
      <% savedmsg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :savedmsg_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/savedmsgs/edit.html.erb
<h1>Editing Savedmsg</h1>

<%= render 'form', savedmsg: @savedmsg %>

<%= link_to 'Show', @savedmsg %> |
<%= link_to 'Back', savedmsgs_path %>

app/views/savedmsgs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Savedmsgs</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @savedmsgs.each do |savedmsg| %>
      <tr>
        <td><%= savedmsg.text %></td>
        <td><%= link_to 'Show', savedmsg %></td>
        <td><%= link_to 'Edit', edit_savedmsg_path(savedmsg) %></td>
        <td><%= link_to 'Destroy', savedmsg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Savedmsg', new_savedmsg_path %>

app/views/savedmsgs/new.html.erb
<h1>New Savedmsg</h1>

<%= render 'form', savedmsg: @savedmsg %>

<%= link_to 'Back', savedmsgs_path %>

app/views/savedmsgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @savedmsg.text %>
</p>

<%= link_to 'Edit', edit_savedmsg_path(@savedmsg) %> |
<%= link_to 'Back', savedmsgs_path %>

app/views/welcome/index.html.erb
<h1>Top-secret 4at za dilur4eta ao</h1>
<%= form_tag({}, multipart:true) do %>
	<%= text_area_tag 'text' %>
	<%= submit_tag 'Submit' %>
<% end %>